const sailAbi = [
    {
        type: "constructor",
        inputs: [
            { name: "selfAddr", type: "address", internalType: "address" },
            { name: "vault_", type: "address", internalType: "contract IVault" },
            { name: "veVC_", type: "address", internalType: "address" },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "allowance",
        inputs: [
            { name: "from", type: "address", internalType: "address" },
            { name: "spender", type: "address", internalType: "address" },
        ],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "approve",
        inputs: [
            { name: "spender", type: "address", internalType: "address" },
            { name: "amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "balanceOf",
        inputs: [{ name: "addr", type: "address", internalType: "address" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "decimals",
        inputs: [],
        outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "decreaseAllowance",
        inputs: [
            { name: "_spender", type: "address", internalType: "address" },
            { name: "_subtractedValue", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "dispense",
        inputs: [],
        outputs: [{ name: "minted", type: "uint256", internalType: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "emissionCurve",
        inputs: [{ name: "t", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "emissionRate",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "emissionStarted",
        inputs: [],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "increaseAllowance",
        inputs: [
            { name: "_spender", type: "address", internalType: "address" },
            { name: "_addedValue", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "initialize",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "listedTokens",
        inputs: [],
        outputs: [{ name: "ret", type: "bytes32[]", internalType: "Token[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lpTokens",
        inputs: [],
        outputs: [{ name: "ret", type: "bytes32[]", internalType: "Token[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "name",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "notifyMigration",
        inputs: [{ name: "n", type: "uint128", internalType: "uint128" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "poolParams",
        inputs: [],
        outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "swapType",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [{ name: "", type: "string", internalType: "string" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "toEmissionTime",
        inputs: [{ name: "timestamp", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "totalSupply",
        inputs: [],
        outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "transfer",
        inputs: [
            { name: "to", type: "address", internalType: "address" },
            { name: "amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "transferFrom",
        inputs: [
            { name: "from", type: "address", internalType: "address" },
            { name: "to", type: "address", internalType: "address" },
            { name: "amount", type: "uint256", internalType: "uint256" },
        ],
        outputs: [{ name: "", type: "bool", internalType: "bool" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "underlyingTokens",
        inputs: [{ name: "lp", type: "bytes32", internalType: "Token" }],
        outputs: [{ name: "", type: "bytes32[]", internalType: "Token[]" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "velocore__execute",
        inputs: [
            { name: "user", type: "address", internalType: "address" },
            { name: "tokens", type: "bytes32[]", internalType: "Token[]" },
            { name: "r", type: "int128[]", internalType: "int128[]" },
            { name: "", type: "bytes", internalType: "bytes" },
        ],
        outputs: [
            { name: "", type: "int128[]", internalType: "int128[]" },
            { name: "", type: "int128[]", internalType: "int128[]" },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "weeklyCumEmission",
        inputs: [{ name: "w", type: "uint256", internalType: "uint256" }],
        outputs: [{ name: "cum", type: "uint256", internalType: "uint256" }],
        stateMutability: "pure",
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            { name: "owner", type: "address", indexed: true, internalType: "address" },
            { name: "spender", type: "address", indexed: true, internalType: "address" },
            { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            { name: "from", type: "address", indexed: true, internalType: "address" },
            { name: "to", type: "address", indexed: true, internalType: "address" },
            { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
        ],
        anonymous: false,
    },

];

module.exports = sailAbi;